// @mostajs/replicator — scaffoldReplicatorService
// Author: Dr Hamid MADANI drmdh@msn.com
// License: AGPL-3.0-or-later
//
// Emits a ready-to-run services/replicator.mjs wrapper into a target project.
// The wrapper loads env (.env + .mostajs/config.env), imports the replicator
// from the app's node_modules, loads the tree.json, and runs an infinite
// sync loop honoring REPLICATOR_INTERVAL_MS.
//
// Called by orm-cli (menu `r → s`) and also exposed as a standalone bin
// `mostajs-replicator-scaffold`.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

export interface ScaffoldOptions {
  /** Target project root. Default : process.cwd() */
  projectDir?: string;
  /** Relative path of the emitted service (default : 'services/replicator.mjs') */
  servicePath?: string;
  /** Preview only — don't write to disk */
  dryRun?: boolean;
  /** Overwrite if the file already exists */
  force?: boolean;
}

export interface ScaffoldResult {
  wrote: boolean;
  path: string;
  action: 'created' | 'skipped (exists)' | 'overwritten' | 'dry-run';
  content: string;
}

/**
 * Emit a `services/replicator.mjs` in the target project. Does NOT touch
 * package.json — that's the caller's responsibility (orm-cli patches
 * `scripts.replicator` + installs concurrently).
 */
export function scaffoldReplicatorService(opts: ScaffoldOptions = {}): ScaffoldResult {
  const projectDir = resolve(opts.projectDir ?? process.cwd());
  const servicePath = opts.servicePath ?? 'services/replicator.mjs';
  const target = resolve(projectDir, servicePath);

  const content = buildTemplate();

  if (opts.dryRun) return { wrote: false, path: target, action: 'dry-run', content };

  if (existsSync(target) && !opts.force) {
    return { wrote: false, path: target, action: 'skipped (exists)', content };
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, 'utf8');

  return {
    wrote: true,
    path: target,
    action: existsSync(target) && opts.force ? 'overwritten' : 'created',
    content,
  };
}

// ----------------------------------------------------------------
// Template — the actual service emitted into user projects.
// ----------------------------------------------------------------
//
// We inline the content as a string so the scaffolder stays single-file
// (no fs.readFile of a template shipped in /templates). This also lets
// future versions update the template without recompiling extra resources.

function buildTemplate(): string {
  return `#!/usr/bin/env node
// services/replicator.mjs — generated by @mostajs/replicator scaffold.
// Runs the replication sync loop for this project.
//
//   npm run replicator            # with the default scripts (see package.json)
//
// Configuration :
//   .env                          PORT / DB_DIALECT / SGBD_URI / etc.
//   .mostajs/replicator-tree.json project topology produced via
//                                 'mostajs' menu r → 'Add replica' / 'Add CDC rule'.
//
// Tuning via env :
//   REPLICATOR_INTERVAL_MS        default 30000 (30s between tick passes)
//   REPLICATOR_TREE               default .mostajs/replicator-tree.json
//   REPLICATOR_QUIET              default 0 — set to 1 to silence per-tick logs

import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// --- Env loading (both files, .env wins over .mostajs/config.env) ---
const loadEnv = (p) => {
  if (!existsSync(p)) return;
  for (const line of readFileSync(p, 'utf8').split('\\n')) {
    if (!line || line.startsWith('#') || !line.includes('=')) continue;
    const i = line.indexOf('=');
    const k = line.slice(0, i).trim();
    const v = line.slice(i + 1).trim();
    if (process.env[k] === undefined) process.env[k] = v;
  }
};
loadEnv(resolve('.mostajs/config.env'));
loadEnv(resolve('.env'));

const TREE = resolve(process.env.REPLICATOR_TREE ?? '.mostajs/replicator-tree.json');
const INTERVAL_MS = Number(process.env.REPLICATOR_INTERVAL_MS ?? 30_000);
const QUIET = process.env.REPLICATOR_QUIET === '1';

const log  = (...a) => { if (!QUIET) console.log('[replicator]', new Date().toISOString(), ...a); };
const warn = (...a) => { console.warn('[replicator]', new Date().toISOString(), ...a); };
const errf = (...a) => { console.error('[replicator]', new Date().toISOString(), ...a); };

// --- Load the replicator lib from the app's node_modules ---
const { ReplicationManager } = await import(resolve('node_modules/@mostajs/replicator/dist/index.js'));
const { ProjectManager }     = await import(resolve('node_modules/@mostajs/mproject/dist/index.js'));

const pm = new ProjectManager();
const rm = new ReplicationManager(pm);

if (existsSync(TREE)) {
  try { await rm.loadFromFile(TREE); log('loaded tree :', TREE); }
  catch (e) { warn('tree load failed :', e.message); }
} else {
  warn(\`no tree at \${TREE} — configure replicas via 'mostajs' menu r first.\`);
}

let running = true;

async function tick() {
  let rules;
  try { rules = rm.listRules(); }
  catch (e) { errf('listRules threw :', e.message); return; }

  const enabled = rules.filter(r => r.enabled);
  if (enabled.length === 0) { log('no enabled rules — idle'); return; }

  for (const r of enabled) {
    try {
      const stats = await rm.sync(r.name);
      log(\`sync \${r.name} — ins=\${stats.inserted ?? 0} upd=\${stats.updated ?? 0} del=\${stats.deleted ?? 0} fail=\${stats.failed ?? 0}\`);
    } catch (e) {
      errf(\`sync \${r.name} threw :\`, e.message);
    }
  }
}

async function loop() {
  while (running) {
    await tick();
    await new Promise(r => setTimeout(r, INTERVAL_MS));
  }
}

const shutdown = async (sig) => {
  log(\`shutting down (\${sig})…\`);
  running = false;
  try { await rm.disconnectAll(); } catch {}
  process.exit(0);
};
process.on('SIGINT',  () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

log(\`starting — interval=\${INTERVAL_MS}ms, tree=\${TREE}\`);
loop().catch(e => { errf('fatal :', e.message); process.exit(1); });
`;
}
